baseURL = "https://hari-krishan.xyz"
languageCode = "en"
DefaultContentLanguage = "en"
title = "I'm Hari"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "I'm Harikrishnan"
author = "Harikrishnan A Nair"
description = "This is my Personal Website"
profilePicture = "img/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["about"]
images = ["images/site-feature-image.png"]
displayMode = "dark"
# Google Site Verification
googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/harikrishnan-a-nair"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/kryptiksage"

[[params.socialIcons]]
icon = "fa-gitlab"
title = "Gitlab"
url = "https://gitlab.com/themoopan"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:harikrishnana253@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Resume"
  weigt = 400
  identifier = "resume"
  url = "/resume.pdf"
